name: Hello World on Tag Push

on:
  push:
    tags:
      - '*'

jobs:
  hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Say Hello World
        run: echo "Hello World"
