name: SVN to GitHub Mirror with Docker
on:
  workflow_dispatch:
      inputs:
        logLevel:
          description: 'Log level'
          required: true
          default: 'warning'
        runID:
          description: 'run_id of the recent run of the github/workflows/createAuthorsFileAndRevNr.yml'
          required: true
          default: '-1'
          
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Benutzerdefinierter Schritt - Ausgabe des Repository-Namens
        run: echo "Der Name des Repositories ist ${{ github.repository }}"

      # Herunterladen der Artefakte (svn-Dateien)
      - name: Herunterladen der author.txt
        uses: actions/download-artifact@v4
        with:
          name: authorFileAnd
          path: ${{ github.workspace }}/temp_jars
          run-id: ${{ inputs.runID }}"
          repository: ${{ github.repository }}/actions/runs/
          github-token: ${{  secrets.TOKEN_GIT }} # token with actions:read permissions on target repo

      - name: Herunterladen der actRevNumber.txt
        uses: actions/download-artifact@v4
        with:
          name: revNumber 
          path: ${{ github.workspace }}/temp_jars
          run-id: ${{ inputs.runID }}"
          repository: ${{ github.repository }}/actions/runs/
          github-token: ${{  secrets.TOKEN_GIT }} # token with actions:read permissions on target repo
      
      - name: Display structure of downloaded files
        run: ls -R ${{ github.workspace }}/temp_jars      
      
      - name: Zeige den Inhalt des Artifacts an
        run: |
          cat ${{ github.workspace }}/temp_jars/authors.txt
          cat ${{ github.workspace }}/temp_jars/actRevNumber.txt
