name: SVN to GitHub Mirror with Docker
on:
  workflow_dispatch:
      inputs:
        environment:
          description: 'Umgebung, in der der Workflow ausgeführt wird'
          required: true
          default: 'production'
          
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Herunterladen der Artefakte (svn-Dateien)
      - name: Herunterladen der Artefakte
        uses: actions/download-artifact@v2
        with:
          name: authorFileAnd
          path: ${{ github.workspace }}/temp_jars

      - name: Zeige den Inhalt des Artifacts an
        run: |
          cat ${{ github.workspace }}/temp_jars
